name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: npm install semantic plugins
        run: npm install @semantic-release/changelog @semantic-release/git @semantic-release/exec
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.DAV_TOKEN }}
        run: npx semantic-release@21